// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Navbar } from "@/components/layout/navbar";
// import { Footer } from "@/components/layout/Footer";
// import { ThemeProvider } from "@/context/ThemeProvider";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "AI chatbot app",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
//       >
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//           <div className="flex flex-col min-h-screen">
//             <Navbar />
//             <main className="flex-1 container mx-auto p-4">{children}</main>
//             <Footer />
//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { ThemeProvider } from "@/components/layout/theme-provider";
import Layout from "@/components/layout/layout";

export const metadata = { title: "My AI Project", description: "AI Portfolio Project" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}

